touch components/charts.md
touch charts/options.md
touch charts/options_style.md
touch charts/options_order.md
touch charts/options_group.md
touch charts/options_filter.md
touch charts/options_exis.md
touch charts/options_summary.md
touch charts/options_value.md
touch charts/options_custom.md
touch charts/options_line.md
touch charts/options_area.md
touch charts/line.md
touch charts/pie.md
touch charts/column.md
touch charts/scatter.md
touch charts/bar.md
touch charts/area.md
touch charts/guage.md
touch charts/radar.md
touch charts/map.md
touch charts/point.md
touch charts/treemap.md
touch charts/funnel.md
touch charts/heatmap.md
touch charts/wordcloud.md
touch charts/gantt.md
touch charts/frame.md
touch charts/calendar.md
touch charts/combine.md
touch charts/customer.md
touch dashboard/home.md
touch dashboard/design.md
touch dashboard/style.md
touch dashboard/layout.md
touch dashboard/param.md
touch dashboard/template.md
touch interact/drag.md
touch interact/zoom.md
touch interact/link.md
touch interact/pivot.md
touch feature/email.md
touch feature/im.md
touch variable_system.md
touch script_system.md
touch chart_manager.md
touch dashboard_manager.md
touch workbook.md
touch favorite.md
touch workspace.md